sudo: required
dist: xenial

language: python
python:
  - '3.6'

install:
  - make install

script:
  - make test

after_script:
  - cd ~

deploy:
  provider: heroku
  api_key:
    secure: HVPkbEDd0MMvmPc7SpwHVM/GdzAnKIeYIUpSaq9Tsc3FkOuC4m8MWjrzGtkV8Aq0KdyZrM6cvUzzOUMp3NwpS/ZISbACpjNpeiN5GpG3q9AjzhzFH2d+2oFCY+KdGxrcB0cJJ3ZgR6dnKBrL8X+PiZSr2VLWAJSOCL85SwSI1XAZwUnh1TMwp9dQoXpANHxGfEspiXfIK/5vkGsQgPB9ESrm4gSDuBCMsns19Kvlcb0eQcLAEn4SGRnO/ZiwnAfbt96SrbP4fzmkak50vU67rEeHuUyxRunjaSgjE2TJUYNF0Wq0Q2Y7mBiGtQyKbE4AKJgDxgGowePMk/rVcLy6lbaxLnUJ8/isPP+Bf8/GYbBu2pyqqZVWFhnb1gRCtPlkqHxYmJP/kDB5LH7uAcrvT6JXxze4YkbTSf/OCunCn6B6XtSvCVwbvluGq6WSB4mJrqLlaO5negIV+/7FdodlPZn9Umjei7Ri7bDEeNYOdWr8ZNA/um3KAF7+HpBLfkCCooMN8sJZJDPFsbzk64ni/V+3i7aOirFFOfP/Mr+sn5HUA//+CgR1yFlfVXj22tL1DRA9kdHuCgfjJWQJemEIYz/AxUY6cpF9zrAEHk0Af1yQm73wyH9Qds/XtFQGgfussy5/pX8PrOj1BM3sQN0P0awET0NyKyWLjqMp9sAUwEs=
  app: kanikumo-engine
