sudo: required
dist: xenial

language: python
python:
  - '3.6'

install:
  - make install

script:
  - make test

after_script:
  - cd ~

deploy:
  provider: heroku
  api_key:
    secure: Di+rVV16DgFrMtkNVGr8SeA23dp5uAoLs6c9vvH2HzeC//oxVHIikteQ3XvFAj8twllFjmB5M7mL5dzzkxFPyd4n83LcGlmJA56bJeekQGEjxGXeEjyXmhThQ2532ryXNV2tfO6urY6Hv8SpnZTSJs7gQLODqOFtTybvr1GGYUud8uKT+1no3X5ox20QbarafKim94nodR+K6cYja0t2+y/SfwFlqQxtKkKbcJ1ESkijlXYlTS+/TfHVq3HZxWYlg3ypKaIX7QMKNEDT8/YVLkkCd1fkqXIhblLN3ooeL3Fk2KC7xN/xpW40LSzw6043vh8K3ZJAmU/sNkDs1HUB35cHxxs+uCOD4VEIAGFAaKOuox6iq1id6dPY/9C6ixAP+JNAPn68Taj1bWh9bOzlz5cCPEsVANWxFKB9Std3tyIoOo6sA908GPrFwM2um5miA8mzvie9v0GXsIyiF483KwbbMjTmhIYJFdQXQlPfkwmfxODWfQgEv6KBw0YMJlXFpUdK96FuNMkJE5Y1jXsa2sE40VqHXOq4L0iqDnk54rgj+CQC9TIHMID7uJkXEAHQhvaHolEekk/bV1SH8XOwRRH5DSu7y7GZ4Dc6OduupPfg4mJb1eHEAqJSr9Ul5zl2+nY8YfC9XX3fXv6OvS7jOEnk5P9oGzpyqd3oKhgGwgc=
  app: kanikumo-engine
