sudo: required
dist: xenial

language: python
python:
  - '3.6'

install:
  - make install

script:
  - make test

after_script:
  - cd ~

deploy:
  provider: heroku
  api_key:
    secure: c7VdGiz8ZAjdSw9M2RNzMXmxRYLkpp8H+ogJUXaMXHKqPLCelWCnUvKnFjIkrCsDnrusLe+M82kIr2SWLMnkAfbxDs3sbhtDTaxcbGjMbVabcocJEpPZySH9a/l5KByuoVd/dQNxQhaN54MKOL6psk3yMLDz7MHRKTK5/35otcTb84OUR8rrT+8BNux8dm6CiKNhekd6xFo0s77L+cD3+UZBTSryUOX3hphmZcymlBu715efzfW2+AWm9RxWnzIFyvfpV7hdceHXC71vkzjH53+VYZuYMBPNJvMB1up59DC8ELPXZ6AJMLcz19UJft7IdVojKs2SspgZf2HrJ3hir36DVjZkhL6YhJ18XRIleo1uBaYNDb5kh2nv/gBv3HQkQvLahtxqkz66TnzSXQIgt/49aT9iyZKKLYtO/gXxS/YuPUb4UVo1FwZM5BnS4tN9qKBsre41lcBkPiSRctF8tyM64J94htQ348f8DXRoHlJLUpng31mVkVfrcoxni19fNJheK3FzDLjGbdAFelrVUPhp06N6HWH07PuMpp9PkVRjA8mWHVM9A9cyytnCwgD32CAwhMnVZjAxHGu5dbj2TruhcTXezkcuY2fkp168Xd40p7mu+XAKvWjsc8uiuRGvM6914F/HtKyrbppj0RwcajrMD0yGB8HZBWSHiDlev7Q=
  app: kanikumo-engine
