sudo: required
dist: xenial

language: python
python:
  - '3.6'

install:
  - make install

script:
  - make test

after_script:
  - cd ~

deploy:
  provider: heroku
  api_key:
    secure: LeE7Sflc7EQQvthQJOQXsYuIoBNCzXibfBFBCTEZpNxtajX6/zZg6VysO7j+QF9uiQmx9d0RdaFTBi0zc6W5q7/JBaXfLJGA/1TFD8oK/4Y63csRQ5hO2m9dFNqOLcMjbWhfBKBVxLGC/e6VzIasHrLchVHBMg0m0RAmNP0pxErhoIktz6640EQ1a+0fJdTtr/IPWH/Z7Dy9IOfdOzzaBQJstxDeTuH2t8UA5HWBa+hAzCfjtD1Dy67OXcYk2FzpTxUMCnI57wToWz03fcmvS3GVBv+Cvf0XbXL4YiorikCGRGNNHIaodfJgpE4U/mV+XI1w7sbGMsig7l0Uri3P+BGhsRuACmHE82oasg+12PCQq373j4NZ1luq898ff6MjwrvAa3XXTynS4NfJU1ZtHIO6tq5qH4wmGK3dVGWTUVD/xxsKv/b12P2M0/HFugHfLhcKmXenyun3DqrHpvly4RWWeXHOWG+M2XLvAI81ONbBL1l+juSfJ6igrWikSi38qb5c12GEwQM46ajZCss0HAY7dI3vFXyCQQvGUI3ASmCSmKqyJK+d99E/fZaoDLHjMqo6NEtWzK2Waug/bAr9bbhkhGEGHHAhpKjCujwZXqR4z3PXM8xRBbO71Wjr1/D0nvyV9E4+Wu6snleiNxqVTyHcDhAtOyEdpdUKDIEKRso=
  app: kanikumo-engine
