sudo: required
dist: xenial

language: python
python:
  - '3.6'

install:
  - make install

script:
  - make test

after_script:
  - cd ~

deploy:
  provider: pypi
  user: dvdantunes
  password:
    secure: nkz8pYVfrXVBlrgCpiT09ltaB7p2Sbk+MzJxrdnZXF2o3oyXjTS9EOKtw6G0AH5t0yFnb/y7YhLmeAZmhrxWwuT26vi7hbSCOwBYPdIF53kUnrGh0M3d276xqyACy+wssaxa/YHlG92aYUswUT3oZwUBbKdqV0Ggbo5fwIrmiHnTAk9zaN3y7eSXsPCmTkCPEYYXW4vJNcsQEdLLhov/ZYq/Z6/K2vuV/aF121KfUp/Y/yDxNzZ7LDEVd/CUR5Ye4XuXzSpfJtytJUtgJpkb3G+uk/g4MTLuEotQ9CCymaFn8LdhF8fzSx9jyjPojX53Px8cBE4AvA5BiuvI12BW+r6jOBPIrmJTCl2Z4GvK2zXg9iO2QvJGNoOLqPVByrinfgQb+0Xu8TdkpFVvkTdFCxOHjKZ8uLoDc/aEKxh2eG9dRSZCbG4oWk2tEZIh9Su90JwUON233rH2DSTw6kBKKcyLP+bf8TihSnUO6HAS9fS3OIZr5B2oTMs5HjYgCUetFA/wdVgoMlGvq/RqpBc6od/1iMxbYG4oV1xIGtecLp6t5ttxmpL9uonh7ZHCewhvyt8v+0Mm2S3QNnEMrHeWAsITwGLOSrGZtY6iDmVNxaBwo/t7RWX11J4jmPQcQFev+aPtIymJy3zdAzzMBaBB2PSirZiwTWHeTXdlmFyzlzA=
